# Generated by Django 4.1.2 on 2023-01-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_publisheb',
            new_name='is_published',
        ),
    ]
